/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:8d191812-9415-4272-bdb7-57a7e7c655f4",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_XIVNQKOAt",
    "aws_user_pools_web_client_id": "476sq9gqhh7g5hs00ctgevnevc",
    "oauth": {}
};


export default awsmobile;
