// {
//     album: {
//       id: "260iH4R6MRNcDQ79106Icv",
//       images: [
//         {
//           height: 640,
//           url: "https://i.scdn.co/image/ab67616d0000b27327b7fb06450f25598103491d",
//           width: 640,
//         },
//         {
//           height: 300,
//           url: "https://i.scdn.co/image/ab67616d00001e0227b7fb06450f25598103491d",
//           width: 300,
//         },
//         {
//           height: 64,
//           url: "https://i.scdn.co/image/ab67616d0000485127b7fb06450f25598103491d",
//           width: 64,
//         },
//       ],
//       name: "lofi study 2021",
//     },
//     artists: [
//       {
//         external_urls: {
//           spotify: "https://open.spotify.com/artist/3uK7MCVwr7FSxnhNKso4Hi",
//         },
//         href: "https://api.spotify.com/v1/artists/3uK7MCVwr7FSxnhNKso4Hi",
//         id: "3uK7MCVwr7FSxnhNKso4Hi",
//         name: "a girl and a cat",
//         type: "artist",
//         uri: "spotify:artist:3uK7MCVwr7FSxnhNKso4Hi",
//       },
//     ],
//     id: "0NDUuWBh1ykEGtIBtD9tAm",
//     is_playable: true,
//     name: "lofi rain",
//     preview_url:
//       "https://p.scdn.co/mp3-preview/1441a83e255d6398206e9b3d832746957b857faa?cid=a4a54eefacc94480aad3c16bec25c8f6",
//     uri: "spotify:track:0NDUuWBh1ykEGtIBtD9tAm",
//   },

export const songs = [
  {
    answers: ["Waka Waka", "Whenever, Wherever", "Be Mine"],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp",
          },
          href: "https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp",
          id: "0EmeFodog0BfCgMzAIvKQp",
          name: "Shakira",
          type: "artist",
          uri: "spotify:artist:0EmeFodog0BfCgMzAIvKQp",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5ppnlEoj4HdRRdRihnY3jU",
      },
      href: "https://api.spotify.com/v1/albums/5ppnlEoj4HdRRdRihnY3jU",
      id: "5ppnlEoj4HdRRdRihnY3jU",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b27327ddd747545c0d0cfe7595fa",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e0227ddd747545c0d0cfe7595fa",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d0000485127ddd747545c0d0cfe7595fa",
          width: 64,
        },
      ],
      name: "Oral Fixation, Vol. 2 (Expanded Edition)",
      release_date: "2005-11-28",
      release_date_precision: "day",
      total_tracks: 13,
      type: "album",
      uri: "spotify:album:5ppnlEoj4HdRRdRihnY3jU",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp",
        },
        href: "https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp",
        id: "0EmeFodog0BfCgMzAIvKQp",
        name: "Shakira",
        type: "artist",
        uri: "spotify:artist:0EmeFodog0BfCgMzAIvKQp",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/7aBzpmFXB4WWpPl2F7RjBe",
        },
        href: "https://api.spotify.com/v1/artists/7aBzpmFXB4WWpPl2F7RjBe",
        id: "7aBzpmFXB4WWpPl2F7RjBe",
        name: "Wyclef Jean",
        type: "artist",
        uri: "spotify:artist:7aBzpmFXB4WWpPl2F7RjBe",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 218093,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "USSM10600677",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/3ZFTkvIE7kyPt6Nu3PEa7V",
    },
    href: "https://api.spotify.com/v1/tracks/3ZFTkvIE7kyPt6Nu3PEa7V",
    id: "3ZFTkvIE7kyPt6Nu3PEa7V",
    is_local: false,
    name: "Hips Don't Lie",
    popularity: 83,
    preview_url:
      "https://p.scdn.co/mp3-preview/9743b7c0f0f21da20168327a5c3ceb7f81a1df29?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 3,
    type: "track",
    uri: "spotify:track:3ZFTkvIE7kyPt6Nu3PEa7V",
  },
  {
    // Crazy In Love
    answers:["Single Ladies","We Found Love","When Love Takes Over"],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m",
          },
          href: "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
          id: "6vWDO969PvNqNYHIOW5v0m",
          name: "Beyoncé",
          type: "artist",
          uri: "spotify:artist:6vWDO969PvNqNYHIOW5v0m",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/6oxVabMIqCMJRYN1GqR3Vf",
      },
      href: "https://api.spotify.com/v1/albums/6oxVabMIqCMJRYN1GqR3Vf",
      id: "6oxVabMIqCMJRYN1GqR3Vf",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b27345680a4a57c97894490a01c1",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e0245680a4a57c97894490a01c1",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d0000485145680a4a57c97894490a01c1",
          width: 64,
        },
      ],
      name: "Dangerously In Love",
      release_date: "2003-06-24",
      release_date_precision: "day",
      total_tracks: 15,
      type: "album",
      uri: "spotify:album:6oxVabMIqCMJRYN1GqR3Vf",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m",
        },
        href: "https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m",
        id: "6vWDO969PvNqNYHIOW5v0m",
        name: "Beyoncé",
        type: "artist",
        uri: "spotify:artist:6vWDO969PvNqNYHIOW5v0m",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3nFkdlSjzX9mRTtwJOzDYB",
        },
        href: "https://api.spotify.com/v1/artists/3nFkdlSjzX9mRTtwJOzDYB",
        id: "3nFkdlSjzX9mRTtwJOzDYB",
        name: "JAY-Z",
        type: "artist",
        uri: "spotify:artist:3nFkdlSjzX9mRTtwJOzDYB",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 236133,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "USSM10305425",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/5IVuqXILoxVWvWEPm82Jxr",
    },
    href: "https://api.spotify.com/v1/tracks/5IVuqXILoxVWvWEPm82Jxr",
    id: "5IVuqXILoxVWvWEPm82Jxr",
    is_local: false,
    name: "Crazy In Love",
    popularity: 76,
    preview_url:
      "https://p.scdn.co/mp3-preview/ce8ace0ec425840416be78db07cf50dd331eed4f?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 1,
    type: "track",
    uri: "spotify:track:5IVuqXILoxVWvWEPm82Jxr",
  },
  {
    answers:["Hey Ya!","Uptown Funk","Remember"],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5SbkVQYYzlw1kte75QIabH",
          },
          href: "https://api.spotify.com/v1/artists/5SbkVQYYzlw1kte75QIabH",
          id: "5SbkVQYYzlw1kte75QIabH",
          name: "Gnarls Barkley",
          type: "artist",
          uri: "spotify:artist:5SbkVQYYzlw1kte75QIabH",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5I0Wf7lRLZArM1K2uQ1AEA",
      },
      href: "https://api.spotify.com/v1/albums/5I0Wf7lRLZArM1K2uQ1AEA",
      id: "5I0Wf7lRLZArM1K2uQ1AEA",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2732cb3f40f7d4114236061f77f",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e022cb3f40f7d4114236061f77f",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048512cb3f40f7d4114236061f77f",
          width: 64,
        },
      ],
      name: "St. Elsewhere",
      release_date: "2006-04-24",
      release_date_precision: "day",
      total_tracks: 14,
      type: "album",
      uri: "spotify:album:5I0Wf7lRLZArM1K2uQ1AEA",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/5SbkVQYYzlw1kte75QIabH",
        },
        href: "https://api.spotify.com/v1/artists/5SbkVQYYzlw1kte75QIabH",
        id: "5SbkVQYYzlw1kte75QIabH",
        name: "Gnarls Barkley",
        type: "artist",
        uri: "spotify:artist:5SbkVQYYzlw1kte75QIabH",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 177466,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "GBAHT0600202",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/1vxw6aYJls2oq3gW0DujAo",
    },
    href: "https://api.spotify.com/v1/tracks/1vxw6aYJls2oq3gW0DujAo",
    id: "1vxw6aYJls2oq3gW0DujAo",
    is_local: false,
    name: "Crazy",
    popularity: 74,
    preview_url:
      "https://p.scdn.co/mp3-preview/b05681b8d3d07a6e0eed3a69d7e6bc221064d8e6?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 2,
    type: "track",
    uri: "spotify:track:1vxw6aYJls2oq3gW0DujAo",
  },
  {
    // usher yeah!
    answers:['Burn','Can U Handle It?','Not In Here'],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/23zg3TcAtWQy7J6upgbUnj",
          },
          href: "https://api.spotify.com/v1/artists/23zg3TcAtWQy7J6upgbUnj",
          id: "23zg3TcAtWQy7J6upgbUnj",
          name: "Usher",
          type: "artist",
          uri: "spotify:artist:23zg3TcAtWQy7J6upgbUnj",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/1RM6MGv6bcl6NrAG8PGoZk",
      },
      href: "https://api.spotify.com/v1/albums/1RM6MGv6bcl6NrAG8PGoZk",
      id: "1RM6MGv6bcl6NrAG8PGoZk",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273365b3fb800c19f7ff72602da",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02365b3fb800c19f7ff72602da",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851365b3fb800c19f7ff72602da",
          width: 64,
        },
      ],
      name: "Confessions (Expanded Edition)",
      release_date: "2004-03-23",
      release_date_precision: "day",
      total_tracks: 21,
      type: "album",
      uri: "spotify:album:1RM6MGv6bcl6NrAG8PGoZk",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/23zg3TcAtWQy7J6upgbUnj",
        },
        href: "https://api.spotify.com/v1/artists/23zg3TcAtWQy7J6upgbUnj",
        id: "23zg3TcAtWQy7J6upgbUnj",
        name: "Usher",
        type: "artist",
        uri: "spotify:artist:23zg3TcAtWQy7J6upgbUnj",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/7sfl4Xt5KmfyDs2T3SVSMK",
        },
        href: "https://api.spotify.com/v1/artists/7sfl4Xt5KmfyDs2T3SVSMK",
        id: "7sfl4Xt5KmfyDs2T3SVSMK",
        name: "Lil Jon",
        type: "artist",
        uri: "spotify:artist:7sfl4Xt5KmfyDs2T3SVSMK",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3ipn9JLAPI5GUEo4y4jcoi",
        },
        href: "https://api.spotify.com/v1/artists/3ipn9JLAPI5GUEo4y4jcoi",
        id: "3ipn9JLAPI5GUEo4y4jcoi",
        name: "Ludacris",
        type: "artist",
        uri: "spotify:artist:3ipn9JLAPI5GUEo4y4jcoi",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 250373,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "USAR10301423",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/5rb9QrpfcKFHM1EUbSIurX",
    },
    href: "https://api.spotify.com/v1/tracks/5rb9QrpfcKFHM1EUbSIurX",
    id: "5rb9QrpfcKFHM1EUbSIurX",
    is_local: false,
    name: "Yeah!",
    popularity: 81,
    preview_url:
      "https://p.scdn.co/mp3-preview/8a5e4f8dce6b1a957e235185a4677841fcaafe90?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 2,
    type: "track",
    uri: "spotify:track:5rb9QrpfcKFHM1EUbSIurX",
  },
  {
    answers:["Get Busy","Give Me The Light","It Wasn't Me"],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9",
          },
          href: "https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9",
          id: "3Isy6kedDrgPYoTS1dazA9",
          name: "Sean Paul",
          type: "artist",
          uri: "spotify:artist:3Isy6kedDrgPYoTS1dazA9",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/32Bu3ETQhR1PFCj3ndDlYf",
      },
      href: "https://api.spotify.com/v1/albums/32Bu3ETQhR1PFCj3ndDlYf",
      id: "32Bu3ETQhR1PFCj3ndDlYf",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b27369ba684e533706bafe248ef3",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e0269ba684e533706bafe248ef3",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d0000485169ba684e533706bafe248ef3",
          width: 64,
        },
      ],
      name: "The Trinity",
      release_date: "2005-09-26",
      release_date_precision: "day",
      total_tracks: 18,
      type: "album",
      uri: "spotify:album:32Bu3ETQhR1PFCj3ndDlYf",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3Isy6kedDrgPYoTS1dazA9",
        },
        href: "https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9",
        id: "3Isy6kedDrgPYoTS1dazA9",
        name: "Sean Paul",
        type: "artist",
        uri: "spotify:artist:3Isy6kedDrgPYoTS1dazA9",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 218573,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "USAT20505520",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/0k2GOhqsrxDTAbFFSdNJjT",
    },
    href: "https://api.spotify.com/v1/tracks/0k2GOhqsrxDTAbFFSdNJjT",
    id: "0k2GOhqsrxDTAbFFSdNJjT",
    is_local: false,
    name: "Temperature",
    popularity: 78,
    preview_url:
      "https://p.scdn.co/mp3-preview/c1ee0ed6fce41fc3ab320cbacdbfcffd197af3a3?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 11,
    type: "track",
    uri: "spotify:track:0k2GOhqsrxDTAbFFSdNJjT",
  },
  {
    // Who's That Chick?
    answers:["SOS","Umbrella","TiK ToK"],
    album: {
      album_type: "single",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/1Cs0zKBU1kc0i8ypK3B9ai",
          },
          href: "https://api.spotify.com/v1/artists/1Cs0zKBU1kc0i8ypK3B9ai",
          id: "1Cs0zKBU1kc0i8ypK3B9ai",
          name: "David Guetta",
          type: "artist",
          uri: "spotify:artist:1Cs0zKBU1kc0i8ypK3B9ai",
        },
      ],
      available_markets: ["GB", "IE"],
      external_urls: {
        spotify: "https://open.spotify.com/album/4nQXx333x2Z5NeJXAyKBxa",
      },
      href: "https://api.spotify.com/v1/albums/4nQXx333x2Z5NeJXAyKBxa",
      id: "4nQXx333x2Z5NeJXAyKBxa",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273361c366377c47b95d8b06474",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02361c366377c47b95d8b06474",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851361c366377c47b95d8b06474",
          width: 64,
        },
      ],
      name: "Who's That Chick? (Remixes) [feat. Rihanna]",
      release_date: "2011-01-09",
      release_date_precision: "day",
      total_tracks: 7,
      type: "album",
      uri: "spotify:album:4nQXx333x2Z5NeJXAyKBxa",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1Cs0zKBU1kc0i8ypK3B9ai",
        },
        href: "https://api.spotify.com/v1/artists/1Cs0zKBU1kc0i8ypK3B9ai",
        id: "1Cs0zKBU1kc0i8ypK3B9ai",
        name: "David Guetta",
        type: "artist",
        uri: "spotify:artist:1Cs0zKBU1kc0i8ypK3B9ai",
      },
    ],
    available_markets: ["GB", "IE"],
    disc_number: 1,
    duration_ms: 201040,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "FRZID1000700",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/1fTH7yRukmCUMI7gjTnUn8",
    },
    href: "https://api.spotify.com/v1/tracks/1fTH7yRukmCUMI7gjTnUn8",
    id: "1fTH7yRukmCUMI7gjTnUn8",
    is_local: false,
    name: "Who's That Chick?",
    popularity: 44,
    preview_url:
      "https://p.scdn.co/mp3-preview/76f84c15961283854291fa140eccd1a6cdb3e524?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 1,
    type: "track",
    uri: "spotify:track:1fTH7yRukmCUMI7gjTnUn8",
  },
  {
    answers:['She Wolf',"Diamonds","Halo"],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp",
          },
          href: "https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp",
          id: "0EmeFodog0BfCgMzAIvKQp",
          name: "Shakira",
          type: "artist",
          uri: "spotify:artist:0EmeFodog0BfCgMzAIvKQp",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/4DyMK9x2gnmRkRa16zHaEV",
      },
      href: "https://api.spotify.com/v1/albums/4DyMK9x2gnmRkRa16zHaEV",
      id: "4DyMK9x2gnmRkRa16zHaEV",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2731f400a1f4d821b00824cf58f",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e021f400a1f4d821b00824cf58f",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048511f400a1f4d821b00824cf58f",
          width: 64,
        },
      ],
      name: "Laundry Service",
      release_date: "2001-11-13",
      release_date_precision: "day",
      total_tracks: 13,
      type: "album",
      uri: "spotify:album:4DyMK9x2gnmRkRa16zHaEV",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp",
        },
        href: "https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp",
        id: "0EmeFodog0BfCgMzAIvKQp",
        name: "Shakira",
        type: "artist",
        uri: "spotify:artist:0EmeFodog0BfCgMzAIvKQp",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 196160,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "NLB630100324",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/2lnzGkdtDj5mtlcOW2yRtG",
    },
    href: "https://api.spotify.com/v1/tracks/2lnzGkdtDj5mtlcOW2yRtG",
    id: "2lnzGkdtDj5mtlcOW2yRtG",
    is_local: false,
    name: "Whenever, Wherever",
    popularity: 74,
    preview_url:
      "https://p.scdn.co/mp3-preview/71832ae5b19c9854ed2241027407be68ae6d7ed8?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 3,
    type: "track",
    uri: "spotify:track:2lnzGkdtDj5mtlcOW2yRtG",
  },
  {
    answers:["Timber","On The Floor","Feel This Moment"],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg",
          },
          href: "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
          id: "0TnOYISbd1XYRBk9myaseg",
          name: "Pitbull",
          type: "artist",
          uri: "spotify:artist:0TnOYISbd1XYRBk9myaseg",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "OM",
        "PA",
        "PE",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TR",
        "TT",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/00zN65JStpVnpJn9ckMsQI",
      },
      href: "https://api.spotify.com/v1/albums/00zN65JStpVnpJn9ckMsQI",
      id: "00zN65JStpVnpJn9ckMsQI",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273956346ed9c201b6de9d3a1a2",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02956346ed9c201b6de9d3a1a2",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851956346ed9c201b6de9d3a1a2",
          width: 64,
        },
      ],
      name: "Pitbull Starring In Rebelution",
      release_date: "2009-08-31",
      release_date_precision: "day",
      total_tracks: 14,
      type: "album",
      uri: "spotify:album:00zN65JStpVnpJn9ckMsQI",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg",
        },
        href: "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
        id: "0TnOYISbd1XYRBk9myaseg",
        name: "Pitbull",
        type: "artist",
        uri: "spotify:artist:0TnOYISbd1XYRBk9myaseg",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "OM",
      "PA",
      "PE",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TR",
      "TT",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VN",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 237120,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "USJAY0900144",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/5RzFJd6W40SDTyZkX6xx45",
    },
    href: "https://api.spotify.com/v1/tracks/5RzFJd6W40SDTyZkX6xx45",
    id: "5RzFJd6W40SDTyZkX6xx45",
    is_local: false,
    name: "I Know You Want Me",
    popularity: 70,
    preview_url:
      "https://p.scdn.co/mp3-preview/6f403695269d85830ce4e3aaa9004331595c2269?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 3,
    type: "track",
    uri: "spotify:track:5RzFJd6W40SDTyZkX6xx45",
  },
  {
    answers:['On The Floor',"Run The World","Shut Up And Drive"],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/2DlGxzQSjYe5N6G9nkYghR",
          },
          href: "https://api.spotify.com/v1/artists/2DlGxzQSjYe5N6G9nkYghR",
          id: "2DlGxzQSjYe5N6G9nkYghR",
          name: "Jennifer Lopez",
          type: "artist",
          uri: "spotify:artist:2DlGxzQSjYe5N6G9nkYghR",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/1l8TpRDfjJjKdtbzNtSycM",
      },
      href: "https://api.spotify.com/v1/albums/1l8TpRDfjJjKdtbzNtSycM",
      id: "1l8TpRDfjJjKdtbzNtSycM",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273a1bf4c1efc808162ac95090f",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02a1bf4c1efc808162ac95090f",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851a1bf4c1efc808162ac95090f",
          width: 64,
        },
      ],
      name: "This Is Me...Then",
      release_date: "2002",
      release_date_precision: "year",
      total_tracks: 13,
      type: "album",
      uri: "spotify:album:1l8TpRDfjJjKdtbzNtSycM",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/2DlGxzQSjYe5N6G9nkYghR",
        },
        href: "https://api.spotify.com/v1/artists/2DlGxzQSjYe5N6G9nkYghR",
        id: "2DlGxzQSjYe5N6G9nkYghR",
        name: "Jennifer Lopez",
        type: "artist",
        uri: "spotify:artist:2DlGxzQSjYe5N6G9nkYghR",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/5pnbUBPifNnlusY8kTBivi",
        },
        href: "https://api.spotify.com/v1/artists/5pnbUBPifNnlusY8kTBivi",
        id: "5pnbUBPifNnlusY8kTBivi",
        name: "Jadakiss",
        type: "artist",
        uri: "spotify:artist:5pnbUBPifNnlusY8kTBivi",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/2x8KDZdSONA3872CnhaAlX",
        },
        href: "https://api.spotify.com/v1/artists/2x8KDZdSONA3872CnhaAlX",
        id: "2x8KDZdSONA3872CnhaAlX",
        name: "Styles P",
        type: "artist",
        uri: "spotify:artist:2x8KDZdSONA3872CnhaAlX",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 187840,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "USSM10212454",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/7LqjznQwfrax7MjQXmxqdQ",
    },
    href: "https://api.spotify.com/v1/tracks/7LqjznQwfrax7MjQXmxqdQ",
    id: "7LqjznQwfrax7MjQXmxqdQ",
    is_local: false,
    name: "Jenny from the Block",
    popularity: 69,
    preview_url:
      "https://p.scdn.co/mp3-preview/dad9d600408f036a267899c2b8b6a73cf6f0cfd4?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 7,
    type: "track",
    uri: "spotify:track:7LqjznQwfrax7MjQXmxqdQ",
  },
  {
    answers:["Whistle","Good Feeling","Dynamite"],
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0jnsk9HBra6NMjO2oANoPY",
          },
          href: "https://api.spotify.com/v1/artists/0jnsk9HBra6NMjO2oANoPY",
          id: "0jnsk9HBra6NMjO2oANoPY",
          name: "Flo Rida",
          type: "artist",
          uri: "spotify:artist:0jnsk9HBra6NMjO2oANoPY",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5j1wrOAOm5KFd17pPiSvle",
      },
      href: "https://api.spotify.com/v1/albums/5j1wrOAOm5KFd17pPiSvle",
      id: "5j1wrOAOm5KFd17pPiSvle",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273f9bd7a6c772ac496015be3f8",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02f9bd7a6c772ac496015be3f8",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851f9bd7a6c772ac496015be3f8",
          width: 64,
        },
      ],
      name: "Mail on Sunday",
      release_date: "2008-03-17",
      release_date_precision: "day",
      total_tracks: 14,
      type: "album",
      uri: "spotify:album:5j1wrOAOm5KFd17pPiSvle",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0jnsk9HBra6NMjO2oANoPY",
        },
        href: "https://api.spotify.com/v1/artists/0jnsk9HBra6NMjO2oANoPY",
        id: "0jnsk9HBra6NMjO2oANoPY",
        name: "Flo Rida",
        type: "artist",
        uri: "spotify:artist:0jnsk9HBra6NMjO2oANoPY",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy",
        },
        href: "https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy",
        id: "3aQeKQSyrW4qWr35idm0cy",
        name: "T-Pain",
        type: "artist",
        uri: "spotify:artist:3aQeKQSyrW4qWr35idm0cy",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    disc_number: 1,
    duration_ms: 231400,
    episode: false,
    explicit: false,
    external_ids: {
      isrc: "USAT20705841",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/0CAfXk7DXMnon4gLudAp7J",
    },
    href: "https://api.spotify.com/v1/tracks/0CAfXk7DXMnon4gLudAp7J",
    id: "0CAfXk7DXMnon4gLudAp7J",
    is_local: false,
    name: "Low",
    popularity: 80,
    preview_url:
      "https://p.scdn.co/mp3-preview/dcddd0ebee02d9142b39d092c823f88201547b7a?cid=a4a54eefacc94480aad3c16bec25c8f6",
    track: true,
    track_number: 5,
    type: "track",
    uri: "spotify:track:0CAfXk7DXMnon4gLudAp7J",
  },
];
